#!/bin/bash

# chkconfig: 345 80 20

# Source function library.
. /lib/lsb/init-functions
path=$path:/user/local/bin

USER=blweb
NAME=blwebapp
APPDIR=/home/blweb/authoring-and-analytics
pidfile=/var/run/$NAME.pid
logfile=/var/log/$NAME.log
forever_dir=/var/local/forever        # Forever root directory.

node=node
forever=`which forever`
awk=awk
sed=sed

start() {
    echo "Starting $NAME node instance: "

    if [ "$foreverid" == "" ]; then
        # Create the log and pid files, making sure that the target use has access to them
        touch $logfile
        chown $USER $logfile

        touch $pidfile
        chown $USER $pidfile

        # Launch the application
        command="$forever start --pidFile $pidfile -l $logfile -o $logfile -e $logfile -a -d $APPDIR"
        su $USER -c "$command"
    else
        echo "Instance already running"
    fi
    RETVAL=$?
}

restart() {
    echo -n "Restarting $NAME node instance : "
    if [ "$foreverid" != "" ]; then
        command="$forever restart -p $forever_dir"
        su $USER -c "$command"
        RETVAL=$?
    else
        start
    fi
}

stop() {
    echo -n "Shutting down $NAME node instance : "
    if [ "$foreverid" != "" ]; then
        command="$forever stop $APPDIR"
        su $USER -c "$command"
    else
        echo "Instance is not running";
    fi
    RETVAL=$?
}

if [ -f $pidfile ]; then
    read pid < $pidfile
else
    pid = ""
fi

if [ "$pid" != "" ]; then
    sed1="s/\x1b\[[0-9]*m//g" # strip colours
    sed2="/$pid/p" # only line with pid
    sed3="s/.*\s\+$pid\s\+\([0-9]\+\).*/\1/" # forever id comes after pid
    foreverid=`su $USER -c "forever list" | $sed $sed1 | $sed -n $sed2 | $sed $sed3`
else
    foreverid=""
fi

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status -p ${pidfile}
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
